version: "3.7"
services:
  safeimage:
    image: arquivo/safeimage
    container_name: 'safeimage'
    volumes:
        - /data/images/pipe:/mnt/jsons
    environment:
        - HOST=$HOSTNAME
    command: sh -c '/code/image-gpu-classifier/start_service.sh'
